Use phpcs config instead of hardcoded standard Don't display phpcbf command

diff --git a/src/pre-commit b/src/pre-commit
--- a/src/pre-commit
+++ b/src/pre-commit
@@ -14,28 +14,28 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "Checking PHP Lint..."
-for FILE in $SFILES
-do
-    php -l -d display_errors=0 $PROJECT/$FILE
-    if [ $? != 0 ]
-    then
-        echo "Fix the error before commit."
-        exit 1
-    fi
-    FILES="$FILES $PROJECT/$FILE"
-done
+if [ "$SFILES" != "" ]
+then
+    echo "Checking PHP Lint..."
+    for FILE in $SFILES
+    do
+        php -l -d display_errors=0 $PROJECT/$FILE
+        if [ $? -ne 0 ]
+        then
+            echo "Please fix the error before commit."
+            exit 1
+        fi
+        FILES="$FILES $PROJECT/$FILE"
+    done
+fi
 
 if [ "$FILES" != "" ]
 then
-    echo "Running Code Sniffer. Code standard PSR2."
-    ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -n -p $FILES
-    if [ $? != 0 ]
+    echo "Running Code Sniffer."
+    ./vendor/bin/phpcs --encoding=utf-8 -n -p $FILES
+    if [ $? -ne 0 ]
     then
-        echo "Fix the error before commit!"
-        echo "Run"
-        echo "  ./vendor/bin/phpcbf $FILES"
-        echo "for automatic fix or fix it manually."
+        echo "Please fix phpcs error before commit!"
         exit 1
     fi
 fi
